### ISSUE TITLE
[Feature Request] Tabbing between cells

### ISSUE THREAD

**Issue by cfonseca88** [dclement8/quill1-table#1]
First and foremost, this is probably the best table module I have seen for version 1 of quill. I don't know much further you plan to take it, but I did happen to find a couple of bugs and possible feature requests.

I was wondering if Tabbing/Shift tabbing can be added for going in-between cells, similar to word.

I'm kind of new in interacting with Github, so if I am missing any information please let me know!

**Comment by dclement8** [comment]
In progress: https://github.com/dclement8/quill1-table/pull/2
Thank you for your contribution

**Comment by dclement8** [comment]
Merged
