### ISSUE TITLE
Would you give a scope to table styles ?

### ISSUE THREAD

**Issue by vtejuf** [dclement8/quill1-table#11]
Hi, there
I found the styles are under '.ql-table' , like: '.ql-editor table、.ql-editor table td'.
this overrides other table's styles which created by me.
so , If you can add a scope to the table styles, it will help me a lot, Thx

**Comment by DylanSalonkee** [comment]
Hi, you can probably use the container's class in your selector, like .ql-container .ql-editor ... for overriding default table styles

**Comment by dclement8** [comment]
Hi, you can probably use the container's class in your selector, like .ql-container .ql-editor ... for overriding default table styles

**Comment by vtejuf** [comment]
all right. but i still think that css should have scope.
