### ISSUE TITLE
Does not work with bubble theme

### ISSUE THREAD

**Issue by e23thr** [dclement8/quill1-table#14]
Using bubble theme, toolbar does not show correctly.

Errors shown as below

> TableToolbar.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at Function.value (TableToolbar.js:3:86)
    at Function.value (TableToolbar.js:10:34)
    at Function.value (TableToolbar.js:31:18)
    at new e (index.js:121:18)
    at t.value (quill.js:6130:28)
    at t.value (quill.js:6774:121)
    at quill.js:6122:17
    at Array.forEach (<anonymous>)
    at t.value (quill.js:6120:41)
    at new e (quill.js:1163:16)

Error in TableToolbar.js at .contains('ql-toolbar')) as below
> export default class TableToolbar {
  static get(quill) {
    if (quill.container.previousSibling && quill.container.previousSibling.classList.contains('ql-toolbar')) {
      return quill.container.previousSibling;
    }
    return null;
  }

**Dependencies**

"quill": "^1.3.7",
"quill1-table": "^1.7.1",

To reproduce:
1. clone this repo
2. Change src/demo.js to use bubble theme
3. build
4. serve

**Comment by dclement8** [comment]
Hi, thank you for your feedback, I added support to bubble theme in version 1.7.2.
However, it is recommended to display the toolbar on single click, otherwise the selection cannot be kept.

```
quill.on('selection-change', range => {
  if (range) {
    quill.theme.tooltip.show();
    quill.theme.tooltip.position(quill.getBounds(range));
  }
});
```
