### ISSUE TITLE
Edge case for delete then undo of cell

### ISSUE THREAD

**Issue by cfonseca88** [dclement8/quill1-table#3]
Thanks for the publish of my recent PR!

I had noticed that if a user deletes texts (with the delete key) beyond the beginning edge of the cell by design it deletes the cell as it should. If a user undo's that action with CTRL+Z or your menu pick it returns the cell. However I noticed delete key no longer deletes text.  It almost seems like the handlers don't get re-added in when cell is added back in.

Let me know if I can provide more info.

Thanks again!

**Comment by dclement8** [comment]
Hello, I was able to reproduce this issue.
Inserting a new line in the re-added cell does not work either.
Neither does inserting a list, a quote or anything else (it's inserted in the cell below).
I won't have time to work on a fix right now but I can prepare one for next month. Don't hesitate to contribute again if you have a fix to suggest!

**Comment by dclement8** [comment]
Fixed in 1.6.1
https://github.com/dclement8/quill1-table/compare/1.6.0...1.6.1
