### ISSUE TITLE
Could not find a declaration file for module 'quill1-table'. 

### ISSUE THREAD

**Issue by Un1xMida** [dclement8/quill1-table#5]
Could not find a declaration file for module 'quill1-table'.

**Comment by dclement8** [comment]
Hi, what did you do to get this error? can you please give me more details? thank you

**Comment by ahmedkhairydev** [comment]
Hello @dclement8 
I'm facing this issue too.
The error appears while the compilation.
![image](https://user-images.githubusercontent.com/15922118/200263332-75a26f89-cada-406e-a365-f32879977391.png)

Can you fix it ASAP?

**Comment by dclement8** [comment]
Hello, I added typescript definition for the last version (1.6.2)
