### ISSUE TITLE
tableOptions is not a function

### ISSUE THREAD

**Issue by ahmedkhairydev** [dclement8/quill1-table#6]
Hello,

When I built a production build and try to use the editor, I faced this error.
![image](https://user-images.githubusercontent.com/15922118/200819215-09f0dd51-b6ba-4237-88d8-1b9a498a941b.png)

Can you help me to solve it?

**Comment by ahmedkhairydev** [comment]
I passed the tableOptions manually then I faced this error.
![image](https://user-images.githubusercontent.com/15922118/200825401-b4b1f1dd-4288-46d1-9102-741f1e2b5f43.png)

![image](https://user-images.githubusercontent.com/15922118/200825423-06807880-9eb7-440a-8f64-40f6c4d2ea06.png)


in the production mode, it doesn't show the default export!

**Comment by ahmedkhairydev** [comment]
@dclement8 I hope this will help you. [Solution](https://stackoverflow.com/a/50437283)

**Comment by ahmedkhairydev** [comment]
@dclement8 any updates?? 👀

**Comment by dclement8** [comment]
Hello, I couldn't reproduce your issue. Have you upgraded quill1-table to 1.6.2? could you provide your webpack config? thank you

**Comment by ahmedkhairydev** [comment]
Hello, Yes I'm using the quill1-table version `1.6.2` with the Angular version `13.2.1`. when I do the `ng build --configuration production` command and try to use the quill editor, I found the sent error.

**Comment by ahmedkhairydev** [comment]
@dclement8 Hey Bro, Did you get the reason for this issue?

**Comment by ahmedkhairydev** [comment]
@dclement8 any updates?

**Comment by dclement8** [comment]
Hello, I can't really help you sorry. I tried compiling using Angular 13.2.1 with Angular CLI and still didn't get the error.

**Comment by ahmedkhairydev** [comment]
@dclement8  Thank You very much, bro. I will investigate also to get it OR fix it

**Comment by ahmedkhairydev** [comment]
Hello Bro @dclement8 

After my investigation, you should export `default` from the library.

Current:
![image](https://user-images.githubusercontent.com/15922118/207595970-f5a9c4c3-2e7e-42bc-8d45-68ddca5cdbaf.png)

Expected:
![image](https://user-images.githubusercontent.com/15922118/207596590-85feb2a1-b4fb-4706-82ef-0481822d63b6.png)

Suggestion Links:
[First One](https://webpack.js.org/configuration/output/#outputlibraryexport)
[Second One](https://webpack.js.org/configuration/output/#outputlibraryexport-1)

**Comment by dclement8** [comment]
Hello, thank you for your suggestion.
I created version 1.6.3 with webpack config change: https://github.com/dclement8/quill1-table/commit/490279b72452a9951ce4c7f7c8bef90ee2bfe3e7#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f
Can you try it please?

**Comment by ahmedkhairydev** [comment]
Thank you, It's working fine now.
