### ISSUE TITLE
hi, I meet some bugs, hope you can improve them when you are free.

### ISSUE THREAD

**Issue by leo-up** [dclement8/quill1-table#7]
hi, dclement8, it's a really nice table for quill1 I never meet, it really helps me a lot.
but I found some bugs, hope you can improve them in coming version.
1. many tables have the <th>head11</th> tag, when you paste them in quill editor, it will convert them to text, it will be nice if you can convert them to  <td>head11</td> before render the quill.
2. when you paste table like this, it does not work, a table convert to common texts, eg.
`<table><tr><td>1111</td><td>222</td></tr><tr><td>333</td><td>444</td></tr></table>`
I checked if you add tag (div or p) in td, then it will work, like this.
`<table><tr><td><p>1111</p></td><td><p>222</p></td></tr><tr><td><p>333</p></td><td><p>444</p></td></tr></table>`
3. if the first td content is empty string, then the table render will have some issue, will miss some td, like this:
`<table><tr><td><p></p></td><td>222</td></tr><tr><td>333</td><td>444</td></tr></table>`
thanks again for you built so nice table for quill1.

**Comment by dclement8** [comment]
Hi, sorry for the late reply,
1/ what is head11 tag? can you provide me an example please?
2/3 Can you send me a code snippet so that I can reproduce it?
Thank you

**Comment by leo-up** [comment]
thanks for care, sorry, it's a mistake.
1. I mean th tag, like this:
`<table><tr><th>1111</th><th>222</th></tr><tr><td>333</td><td>444</td></tr></table>`
can turn into this when render the quill editor:
`<table><tr><td>1111</td><td>222</td></tr><tr><td>333</td><td>444</td></tr></table>`
2. I sent the code snippet above, try this:
`<table><tr><td>1111</td><td>222</td></tr><tr><td>333</td><td>444</td></tr></table>`
when render the quill editor, the table will disappeared, turn into common text.
3. try this code snippet, the td will miss one.
`<table><tr><td><p></p></td><td>222</td></tr><tr><td>333</td><td>444</td></tr></table>`

**Comment by dclement8** [comment]
Ok, I could reproduce your issues, thank you. Fixed in 1.6.4
